apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml_project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/ml-project-backend:latest
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FLASK_ENV
          ports:
            - containerPort: 5000
