apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ml_project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/ml-project-frontend:latest
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_URL
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          ports:
            - containerPort: 3000
